version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      # Set up PostgreSQL (if needed)
      # - run: echo "DATABASE_URL=postgresql://postgres@localhost/dbname" > .env

      # Install project dependencies
      - run: pip install -r requirements.txt

      # Run tests with coverage
      - run: |
          pip install coverage
          coverage run -m pytest
          coverage report -m