version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      # Set up PostgreSQL (if needed)
      # - run: echo "DATABASE_URL=postgresql://postgres@localhost/dbname" > .env

      # Install project dependencies
      - run: pip install -r requirements.txt

      # Run tests with coverage
      - run: |
          pytest --cov
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t 3cd4fe1d-6f77-4465-8c3a-34951b1765fe